### ISSUE TITLE
Also index enums and trait impls

### ISSUE THREAD

**Issue by sgeisler** [rust-corpus/rustql#6]
I just came across this project and I like the idea very much, so thank you for building it!

I found it in a search for a way to enforce certain standard trait implementations on e.g. Error types that are often forgotten to implement. For that I'd need access to trait implementations for structs and enums though. If anyone ever continues to develop this project this might be an interesting use case to look at.

**Comment by vakaras** [comment]
@sgeisler In general, this is a complicated query because of things like
```rust
impl<T> Trait for T where T: X {}
```

However, if you do not care about generics, the information should be already in [the database](https://github.com/rust-corpus/qrates/blob/c3c4313ca1afa87bf4ae7cff3adeccc488a2cf06/database/src/schema.dl#L374-L377).

**Comment by vakaras** [comment]
You can find some documentation about the database format and writing custom queries [here](https://rust-corpus.github.io/qrates/database_structure.html).

**Comment by sgeisler** [comment]
That seemed to work quite well. Thanks a lot!
